name: CI - Node.js 22 + Docker Compose + Lint/Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Allow wait-for-it execution
        run: chmod +x ./wait-for-it.sh

      - name: Start containers with Docker Compose
        run: docker compose up -d --build

      - name: Wait until PostgreSQL starts
        run: ./wait-for-it.sh localhost:5432 --timeout=30 --strict -- echo "PostgreSQL is ready"

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Stop Containers
        if: always()
        run: docker compose down --volumes

